import * as nodeMap from './index.node';
import { UnionSyntaxNode, UnionSyntaxNodeType } from '../base';

export type ExpressionNode = UnionSyntaxNode<typeof nodeMap>;
export type ExpressionNodeType = UnionSyntaxNodeType<typeof nodeMap>;

export * from './assign-op';
export * from './assignment';
export * from './binary-operation';
export * from './boolean-literal';
export * from './call-argument-list';
export * from './conditional';
export * from './expression';
export * from './function-call-options';
export * from './function-call';
export * from './hex-string-literal';
export * from './identifier';
export * from './index-access';
export * from './index-range-access';
export * from './inline-array-expression';
export * from './inline-array';
export * from './literal';
export * from './member-access';
export * from './named-argument';
export * from './new-expr';
export * from './number-literal';
export * from './payable-conversion';
export * from './primary-expression';
export * from './string-literal';
export * from './tuple-expression';
export * from './tuple';
export * from './unary-operation';
export * from './unicode-string-literal';
export * from './user-definable-operator';
